# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    name: Build
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: checking the dir
        run: pwd
      - name: checking the contents
        run: ls -la
        
      - name: Linting the terraform code
        run: sudo docker run --rm -v $(pwd):/data -t ghcr.io/terraform-linters/tflint
        
#       - name: checking the contents
#         run: cat report

  

          
